# Generated by Django 4.1 on 2024-03-02 12:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_category', models.CharField(choices=[('AR', 'ART'), ('PH', 'PHOTOGRAPHY'), ('SU', 'SCULPTURE'), ('CR', 'CRAFTS')], default='AR', max_length=2)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VenueModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=40)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('contact_email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('contact_phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('venue_category', models.CharField(blank=True, choices=[('MU', 'MUSEUM'), ('GA', 'GALLERY')], max_length=2, null=True)),
                ('hosting_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosts', to='api.eventmodel')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(related_name='wishlists', to='api.eventmodel')),
                ('venues', models.ManyToManyField(related_name='wishlists', to='api.venuemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('events', models.ManyToManyField(related_name='itineraries', to='api.eventmodel')),
                ('venues', models.ManyToManyField(related_name='itineraries', to='api.venuemodel')),
            ],
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='venue',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_in', to='api.venuemodel'),
        ),
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tickets', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.eventmodel')),
            ],
        ),
    ]
