# Generated by Django 4.2.4 on 2024-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='test_field',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
