# Generated by Django 4.2.4 on 2024-03-04 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usermodel_forgot_password_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='test_field',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
