# Generated by Django 4.2.4 on 2024-03-14 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_itinerarymodel_venues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerarymodel',
            name='venues',
            field=models.ManyToManyField(null=True, related_name='itineraries', to='api.venuemodel'),
        ),
    ]
