# Generated by Django 4.2.4 on 2024-03-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_eventmodel_lat_alter_eventmodel_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
