# Generated by Django 4.2.4 on 2024-03-04 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermodel_test_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='test_field',
            new_name='forgot_password_otp',
        ),
    ]
