# Generated by Django 4.2.4 on 2024-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_eventmodel_lat_alter_eventmodel_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuemodel',
            name='hosting_events',
            field=models.ManyToManyField(related_name='hosts', to='api.eventmodel'),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='venue_category',
            field=models.CharField(blank=True, choices=[('MU', 'MUSEUM'), ('GA', 'GALLERY')], max_length=2),
        ),
    ]
