# Generated by Django 4.2.4 on 2024-03-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_test_field_usermodel_forgot_password_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='forgot_password_otp',
            new_name='forgot_pass_otp',
        ),
    ]
