# Generated by Django 4.2.4 on 2024-03-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_forgot_password_otp_usermodel_forgot_pass_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='forgot_pass_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
